hc: 1.1354
gravity: 9.80665
dt: 0.001
control_frequency: 1000
plan_frequency: 100
joint_state_topic: "/atlas_raisim_ros/joint_states"
com_topic: "/atlas_raisim_ros/CoM"
odom_topic: "/atlas_raisim_ros/odom"
zmp_topic: "/atlas_raisim_ros/ZMP"
wrenchLLeg_topic: "/atlas_raisim_ros/LLeg/force_torque_states"
wrenchRLeg_topic: "/atlas_raisim_ros/RLeg/force_torque_states"
LLegodom_topic: "/atlas_raisim_ros/LLeg/odom"
RLegodom_topic: "/atlas_raisim_ros/RLeg/odom"
gait_phase_topic: "/atlas_raisim_ros/gait_phase"
#CoM Admittance Control Parameters
enabled: True
CoM_admittance_gain_x: 1.1
CoM_admittance_gain_y: 0.9
ZMP_proportional_gain_x: 2.0
ZMP_proportional_gain_y: 2.0
DCM_proportional_gain_x: 7.0
DCM_proportional_gain_y: 7.0
DCM_Integral_gain_x: 0
DCM_Integral_gain_y: 0

Linear_task_gain: 0.008
Angular_task_gain: 0.008
CoM_task_weight: 1.0
LLeg_task_weight: 10.0
RLeg_task_weight: 10.0
Torso_task_weight: 0.1
Head_task_weight: 1.0e-2
LHand_task_weight: 1.0e-2
RHand_task_weight: 1.0e-2
DOF_weight: 5.0e-3
DOF_gain: 0.02