hc: 0.263
gravity: 9.80665
dt: 0.01
control_frequency: 100
joint_state_topic: "/nao_raisim_ros/joint_states"
com_topic: "/nao_raisim_ros/CoM"
odom_topic: "/nao_raisim_ros/odom"
zmp_topic: "/nao_raisim_ros/ZMP"
modelname: "/home/master/catkin_ws/src/whole_body_ik/share/urdf/nao.urdf"

#CoM Admittance Control Parameters
enabled: False
CoM_admittance_gain_x: 0.02
CoM_admittance_gain_y: 0.02
ZMP_proportional_gain_x: 0.5
ZMP_proportional_gain_y: 0.5
DCM_proportional_gain_x: 1.5
DCM_proportional_gain_y: 1.5
DCM_Integral_gain_x: 0
DCM_Integral_gain_y: 0

Linear_task_gain: 5
Angular_task_gain: 0.025
CoM_task_weight: 1
LLeg_task_weight: 10
RLeg_task_weight: 10
Torso_task_weight: 5.0e-3
Head_task_weight: 5.0e-4
LHand_task_weight: 5.0e-4
RHand_task_weight: 5.0e-4
DOF_weight: 5.0e-5
DOF_gain: 0.1