hc: 0.895
gravity: 9.80665
dt: 0.001
control_frequency: 1000
plan_frequency: 100
joint_state_topic: "/talos_raisim_ros/joint_states"
com_topic: "/talos_raisim_ros/CoM"
odom_topic: "/talos_raisim_ros/odom"
zmp_topic: "/talos_raisim_ros/ZMP"
wrenchLLeg_topic: "/talos_raisim_ros/LLeg/force_torque_states"
wrenchRLeg_topic: "/talos_raisim_ros/RLeg/force_torque_states"
LLegodom_topic: "/talos_raisim_ros/LLeg/odom"
RLegodom_topic: "/talos_raisim_ros/RLeg/odom"
gait_phase_topic: "/talos_raisim_ros/gait_phase"
#CoM Admittance Control Parameters
enabled: True
CoM_admittance_gain_x: 1.25
CoM_admittance_gain_y: 1.25
ZMP_proportional_gain_x: 2.5
ZMP_proportional_gain_y: 2.5
DCM_proportional_gain_x: 7.5
DCM_proportional_gain_y: 7.5
DCM_Integral_gain_x: 0
DCM_Integral_gain_y: 0

foot_damping_control_gain: 0.0000
foot_damping_control_time_constant: 0.001
base_damping_control_gain: 0
base_damping_control_time_constant: 0.001

Linear_task_gain: 0.001
Angular_task_gain: 0.05
CoM_task_weight: 0.1
LLeg_task_weight: 1.0
RLeg_task_weight: 1.0
Torso_task_weight: 0.05
Head_task_weight: 1.0e-3
LHand_task_weight: 1.0e-3
RHand_task_weight: 1.0e-3
DOF_weight: 5.0e-4
DOF_gain: 0.01
